using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using Utilities;

namespace BussinessLogicLayer
{
    public class MailSender
    {
        public static void SendMail(string receiver, Attachment attachment)
        {
            var envValues = EnvReader.Read("emailCredentials.env");

            MailAddress to = new(receiver);
            MailAddress from = new(envValues["SENDER"]);

            MailMessage message = new(from, to);

            message.Subject = "Resume";
            message.Body = "This is an autogenerated resume by Team Punisher";
            message.Attachments.Add(attachment);

            SmtpClient smtp = new SmtpClient();

            smtp.Host = envValues["HOST"];
            smtp.Port = 587;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new NetworkCredential(envValues["SENDER"], envValues["PASSWORD"]);
            smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
            
            smtp.Send(message);
        }
    }
}
